### ISSUE TITLE
Not All Programs Work

### ISSUE THREAD

**Issue by jb12sterli** [belowaverage-org/webdows#31]
Tried opening task manager and got the error
![2016-12-29 2](https://cloud.githubusercontent.com/assets/24300089/21548910/aed0337e-cdb4-11e6-9d03-1712e715eef3.png)

Tried opening file explorer and got this

![2016-12-29 3](https://cloud.githubusercontent.com/assets/24300089/21548947/cfefcf74-cdb4-11e6-8917-55a9ffce15cd.png)

Do you know what could cause this?

**Comment by krisdb2009** [comment]
Thanks for showing interest in Webdows, These programs are not 100% finished yet. I have not released any version of Webdows just yet.

**Comment by krisdb2009** [comment]
Youtube Extractor is now working.

**Comment by krisdb2009** [comment]
The YouTube Extractor is now working as it should. 590992da13a3253059344a8fb672ebaf727946c9

**Comment by krisdb2009** [comment]
Registry Editor is 100% functional now.

**Comment by krisdb2009** [comment]
These are ongoing issues, and all things mentioned above are related to other open tickets.

Closing this for now as duplicate.
