### ISSUE TITLE
Clicking Credits Menu also shows About menu.

### ISSUE THREAD

**Issue by Chew** [belowaverage-org/webdows#32]
Just throwing this out here making sure it's known, not sure if it's intentional or not but here we are

![e634c23bb0121f4d63f1540aeb50aa18](https://cloud.githubusercontent.com/assets/8278263/22848070/5e89ca36-efb7-11e6-9d45-c37af4e7da35.gif)

**Comment by krisdb2009** [comment]
Its kinda intentional, but I will fix this since its awfully ugly. Thanks for the tip!

**Comment by Chew** [comment]
the point I was making was the about menu shows up as well as the credits when you click the credits when only credits should, right?

**Comment by krisdb2009** [comment]
When I programmed that part I made it intentional that it opens both, since credits was a part of the "About Webdows" program. I can easily fix this and will.

Take a look at this file to see how it is embedded: https://github.com/belowaverage-org/webdows/blob/master/webdows/webver.js

```
this.body.find('button.credits')
    .css({'width':'80px','height':'20px','position':'absolute','bottom':'10px','left':'10px'})
    .click({win: this}, function(e) {
        new explorer.window()
        .closeWith(e.data.win)
        .controls([])
        .title('Credits')
        .resize(450, 400)
        .center()
        .icon('webdows/resources/icons/info.ico')
        .callback(function() {
            this.body
            .html('<pre style="user-select:text;margin:0px;top:0px;left:0px;border:0px;position:absolute;width:100%;height:100%;word-wrap:break-word;white-space:pre-wrap;"></pre>')
            .find('pre')
            .load('credits.txt');
        });
    });
```
