### ISSUE TITLE
Gain independence from jQuery UI.

### ISSUE THREAD

**Issue by krisdb2009** [belowaverage-org/webdows#51]
- [x] - Create drag API
- [x] - Switch windows to the drag API
- [x] - Switch window resizing to the drag API
- [x] - Switch taskbar dragging to the drag API

**Comment by Chew** [comment]
This sounds like the start of a new country instead of programming

**Comment by krisdb2009** [comment]
And its not gonna be easy either

**Comment by krisdb2009** [comment]
Created new explorer.drag method for dragging windows and other various things for future development. Explorer windows no longer use jqui for dragging. b4ad500f3766e3bb75f018f485ab9c21d4b6f04f
