### ISSUE TITLE
Sanitize HTML for CMD.js

### ISSUE THREAD

**Issue by krisdb2009** [belowaverage-org/webdows#63]
^

**Comment by Chew** [comment]
Could be a little bit more descriptive.

**Comment by krisdb2009** [comment]
![1](https://cloud.githubusercontent.com/assets/8226974/26118651/b4d1ef7e-3a38-11e7-89e7-f57a61dced39.PNG)
![2](https://cloud.githubusercontent.com/assets/8226974/26118650/b4cd7912-3a38-11e7-9b28-2beb7c8ec028.PNG)

**Comment by krisdb2009** [comment]
I need to make the CMD.js file strip out HTML that is sent to it.

This can be fixed easily by using $.text() rather than $.append() which I think is what is used.

**Comment by Chew** [comment]
Ah okay

**Comment by krisdb2009** [comment]
Fixed. CMD.js no longer renders html typed into the text field.
