### ISSUE TITLE
Clicking "Credits" on the main menu brings up a missing file error.

### ISSUE THREAD

**Issue by Chew** [belowaverage-org/webdows#69]
![9f73ccf00d984a2c761e2a87e81b025d](https://user-images.githubusercontent.com/8278263/29750295-ad2c1392-8b02-11e7-8e43-e1a410f7b1ab.png)
I was able to fix this by putting a credits.txt on the main `/` directory of the repository. (Check my outdated fork to see).
It appears a previous commit, unsure of intentionality, deleted it.

**Comment by krisdb2009** [comment]
I removed this because the I took some credited components out of Webdows.

I need to re-evaluate what I use and build a new credit file.
