### ISSUE TITLE
http://belowaverage-org.github.io/webdows/ is an invalid url

### ISSUE THREAD

**Issue by Chew** [belowaverage-org/webdows#71]
https://github.com/belowaverage-org/webdows/commit/52ea36618301d7aee26104fa6e5452403608fe4f this commit changed the url but the destination is invalid

**Comment by krisdb2009** [comment]
Yep, it used to be for the github pages.

Removed in latest commit:  6b6f924c3b014d72d22b0dd374fd4dc2f1102f3d

**Comment by Chew** [comment]
If you add “Fixes #issuenum” to a commit message, it will close that issue

**Comment by krisdb2009** [comment]
Oh, nice thanks for the tip!
