### ISSUE TITLE
You are able to drag a window below the bottom dock.

### ISSUE THREAD

**Issue by Chew** [belowaverage-org/webdows#75]
Now I don't usually use windows but when I do, you can't drag the window below the dock, it just full-screens the window.

I notice it's partially fixed because I let go of my mouse when the window was below the dock and it stuck until I clicked again.

![0bd9abb163baca4116c78b7b8a152a76](https://user-images.githubusercontent.com/8278263/30184232-03bfd0de-93e3-11e7-9d8e-ee9ec8fc62bd.gif)

**Comment by krisdb2009** [comment]
In windows 7 - 10 windows can easily be dragged underneath the taskbar. There is no preventative measures created by Microsoft to keep the window from being stuck underneath.

Also if a there is any gap between the cursor and window, the mouse up event will not fire. Therefore I cannot make the mouse "Let go".

**Comment by Chew** [comment]
Not the entire window as shown in the gif, the very top doesn't go below the taskbar (at least for me on 8)

**Comment by krisdb2009** [comment]
Can you explain?

**Comment by Chew** [comment]
~_ignore the desktop nonsense it's a school computer_~

The window doesn't fully go below the task bar.

**Windows 8 as a reminder**

![2017-09-08_09-22-08](https://user-images.githubusercontent.com/8278263/30216064-692f40a0-9477-11e7-8b14-f3fa51b7848a.gif)

**Comment by Chewsterchew** [comment]
bump

**Comment by krisdb2009** [comment]
I am able to on Windows 10
https://drive.google.com/file/d/0B2ucIgds7v9RbnAyWWNrQWtZamM/view

**Comment by Chew** [comment]
windows is weird dude this is why I use a mac xD
Guess it's dependent on OS.
What happens if you let go of the window below the taskbar?

**Comment by krisdb2009** [comment]
It stuck, and you have to use Win + Arrow key to get it back.
