### ISSUE TITLE
ADD THIS TO THE APP STOR

### ISSUE THREAD

**Issue by oscdows** [belowaverage-org/webdows#80]

**Comment by Chew** [comment]
This is a website, not an app. Can you explain yourself?

**Comment by krisdb2009** [comment]
Chew, this is an APP on the windows store and android now.
Either way this issue makes no sense to me.

**Comment by Chew** [comment]
WHaaaaaaaaaaa. Links to both?

**Comment by krisdb2009** [comment]
https://www.microsoft.com/store/productId/9NG955X8496V

https://play.google.com/store/apps/details?id=org.belowaverage.webdows&hl=en

**Comment by Chew** [comment]
Oh that's pretty neat.

**Comment by krisdb2009** [comment]
Yea, the one for android is super outdated tho. I need a good app package.

You can check out my apps code here: https://github.com/krisdb2009/ABS

**Comment by oscdows** [comment]
I mean ios

**Comment by krisdb2009** [comment]
I will work on it today.
Thanks for the suggestion.
May I ask where you found out about Webdows?
Also what device you are using it on?

**Comment by oscdows** [comment]
Well it all started on my Xbox I was on the Xbox store and I I found the app one day I went on my computer and I looked it up on google and I picked the rite link and downloaded it and one day I found a link on google play and ges what I found yes webdows I was so angry since I hate android and I will be happy waking up tomorrow download this app without having to download software thanks and I hope your app will be on stage when apple stops releasing apps and make it compatible with iOS 10

**Comment by krisdb2009** [comment]
Turns out you need to pay 90 dollars a year to put an app on Apples app store

**Comment by krisdb2009** [comment]
If you want to use webdows on iOS visit https://webdows.belowaverage.org/

**Comment by Chew** [comment]
Yeah it's pretty expensive but it's worth it

**Comment by krisdb2009** [comment]
Yea, I don't have that kind of money. I will develop the app however and publish it on github.

**Comment by Chew** [comment]
Pretty neat

**Comment by krisdb2009** [comment]
@Chewsterchew, do you have a mac? I have created the app in cortova for IOS, and need a mac to compile it.

I can give you access to the source if you do.

**Comment by Chew** [comment]
Yes, I own a mac.

**Comment by krisdb2009** [comment]
@Chewsterchew Cool, would you be willing to try and compile this for me?

**Comment by Chew** [comment]
When I get home later, sure!

**Comment by krisdb2009** [comment]
Cool, its a private repo, so you will have to join as a collaborator: https://github.com/krisdb2009/cordova-webdows/invitations

All you will need to do is clone this repo, clone the submodule, then run "cordova run ios".

Let me know if you need any help. Also there is some documentation on installing cordova on their website. https://cordova.apache.org/

**Comment by krisdb2009** [comment]
- [x] [Google Play](https://play.google.com/store/apps/details?id=org.belowaverage.webdows)
- [x] [Microsoft Store](https://www.microsoft.com/en-us/store/p/webdows/9ng955x8496v)
- [ ] Apple App Store

**Comment by Chew** [comment]
Surprise! I have Apple developer and have actual experience with Cordova now.

**Comment by Chew** [comment]
Are we still planning on releasing?

**Comment by krisdb2009** [comment]
Yes!

Here is the repo containing the cordova build that is currently in use on android:

https://github.com/belowaverage-org/Webdows-Cordova

I can give you some access if you would like to help maintain by updating cordova or whatever it needs since it is an old build.

**Comment by Chew** [comment]
Sure! For the profile I need some information:
App name (This will go on the App Store)
Bundle ID: (Those java things, like org.belowaverage.webdows maybe?)

**Comment by Chew** [comment]
I also need a 1024x1024 app icon

**Comment by Chew** [comment]
[Here's me messing around with it a bit](https://cdn.discordapp.com/attachments/148195924567392257/530784878078328853/video.mov)

I have to move the page down to get to the windows dock. All I did was pull this repo into the `www` folder then built. Otherwise it runs fairly well!

**Comment by krisdb2009** [comment]
App name: Webdows
Bundle ID you put is perfect.

Looks great!  Glad it wasn't too hard to build

**Comment by Chew** [comment]
Any way we can fix the dock having to scroll the page to get to?

**Comment by Chew** [comment]
Probably looks way better on iPad

**Comment by Chew** [comment]
If you have an Apple ID I can give you admin permissions over the app, let me know

**Comment by krisdb2009** [comment]
The reason you have to scroll is because there is a minimum size the screen has to be to accommodate the start menu in webdows.

Also, I do have an apple ID, but I need to make sure I can still sign in.

**Comment by krisdb2009** [comment]
AppleID: dylan@belowaverage.org

**Comment by Chew** [comment]
Alright, added. Any way we can IM? This github issue doesn't seem like a proper place for this lol

**Comment by krisdb2009** [comment]
Email for now will work for me: mine is dylan@belowaverage.org, shoot me an email so we can keep discussing, i have an icon you can use.

**Comment by Chew** [comment]
Alright, see you there.

**Comment by krisdb2009** [comment]
Closing since apple will not accept this as an app.

**Comment by Chew** [comment]
Actually, they might. Apparently we just need to add the option of only showing one window at a time.
