### ISSUE TITLE
Go home calculator, youŕe drunk.

### ISSUE THREAD

**Issue by MrJoCrafter** [belowaverage-org/webdows#83]
This.
![screenshot 2017-12-01 at 2 20 13 pm](https://user-images.githubusercontent.com/14947881/33501659-0031b5f6-d6a3-11e7-9051-2e0a5f6ba0e8.png)

![screenshot 2017-12-01 at 2 20 25 pm](https://user-images.githubusercontent.com/14947881/33501662-0462bcb0-d6a3-11e7-90fb-b8f5ae149ee5.png)
This

**Comment by krisdb2009** [comment]
![infinity](https://user-images.githubusercontent.com/8226974/33518131-d1307196-d75d-11e7-97cd-d876fb1697c3.PNG)
The calculator works by running[ eval(); ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval) on the input. The browser is what returns "Infinity" I will try other browsers to see if something different happens.

What should the calculator report when it divides by zero? Microsoft Windows 10 returns "Cannot divide by zero"

**Comment by Chew** [comment]
My mac returns:
`Not a number`

My ti-84 calculator returns:
`Error: Attempted to divide number by 0. Calculation fails.`

Siri returns:
<img width="284" alt="35670d67b33d59dc7cf06db273b8c74c" src="https://user-images.githubusercontent.com/8278263/33519317-2135a934-d76a-11e7-9033-196480ebf284.png">

**Comment by krisdb2009** [comment]
Google also reports this:
![capture](https://user-images.githubusercontent.com/8226974/33519694-03309f7e-d77a-11e7-88d5-974fd78e173a.PNG)
@MrJoCrafter , What is the issue with the calculator in Webdows?

**Comment by Chew** [comment]
Bing reports this:
![38016531fd9abe162e1ca3ff1e6f32ae](https://user-images.githubusercontent.com/8278263/33520117-2ccb4de8-d77a-11e7-9b96-4e1ea6772694.png)

**Comment by ds33d** [comment]
Calculator will now display "Cannot divide by zero" when dividing by zero
 
![image](https://user-images.githubusercontent.com/25713076/33559239-29d88c98-d8da-11e7-8b1c-8ea8f6c121f4.png)
